// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentaFacil.Vehicles.Infrastructure.Persistence;

#nullable disable

namespace RentaFacil.Vehicles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VehiclesDbContext))]
    [Migration("20260904021125_InicialVehiculos")]
    partial class InicialVehiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentaFacil.Vehicles.Domain.Entities.BloqueoDisponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReferenciaExternaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaExternaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Bloqueos_ReferenciaExternaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("BloqueosDisponibilidad", (string)null);
                });

            modelBuilder.Entity("RentaFacil.Vehicles.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehiculos_Placa");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Vehiculos_Tipo");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("RentaFacil.Vehicles.Domain.Entities.BloqueoDisponibilidad", b =>
                {
                    b.HasOne("RentaFacil.Vehicles.Domain.Entities.Vehiculo", null)
                        .WithMany("Bloqueos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("RentaFacil.Vehicles.Domain.ValueObjects.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("BloqueoDisponibilidadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("FechaFin");

                            b1.Property<DateOnly>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("FechaInicio");

                            b1.HasKey("BloqueoDisponibilidadId");

                            b1.ToTable("BloqueosDisponibilidad");

                            b1.WithOwner()
                                .HasForeignKey("BloqueoDisponibilidadId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("RentaFacil.Vehicles.Domain.Entities.Vehiculo", b =>
                {
                    b.OwnsOne("RentaFacil.Vehicles.Domain.ValueObjects.Dinero", "TarifaDiaria", b1 =>
                        {
                            b1.Property<Guid>("VehiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TarifaDiariaMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TarifaDiariaMonto");

                            b1.HasKey("VehiculoId");

                            b1.ToTable("Vehiculos");

                            b1.WithOwner()
                                .HasForeignKey("VehiculoId");
                        });

                    b.Navigation("TarifaDiaria")
                        .IsRequired();
                });

            modelBuilder.Entity("RentaFacil.Vehicles.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("Bloqueos");
                });
#pragma warning restore 612, 618
        }
    }
}
